"""Adding profile_image to User model

Revision ID: 217ae13f3380
Revises: 17eab0bed38f
Create Date: 2025-05-16 13:36:50.768636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217ae13f3380'
down_revision = '17eab0bed38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=500), nullable=True))

    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('friend_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], )
    )
    # ### end Alembic commands ###
