"""empty message

Revision ID: 5d46d9e20127
Revises: 96b19a4c98a9
Create Date: 2025-05-13 17:55:36.535517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d46d9e20127'
down_revision = '96b19a4c98a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_friend', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_column('is_friend')

    # ### end Alembic commands ###
